{
  "error": {
    "error_code": 5,
    "error_msg": "User authorization failed: access_token was given to another ip address.",
    "request_params": [
      {
        "key": "extended",
        "value": "1"
      },
      {
        "key": "v",
        "value": "5.131"
      },
      {
        "key": "user_id",
        "value": "4321550"
      },
      {
        "key": "method",
        "value": "groups.get"
      },
      {
        "key": "oauth",
        "value": "1"
      }
    ]
  }
}